services:
    repair-app:
        container_name: repair-app
        build:
            context: .
            dockerfile: ./docker/development/Dockerfile
        volumes:
            - .:/app
        env_file:
            - .env
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - repair-postgres

    repair-postgres:
        image: postgres:16-alpine
        volumes:
            - repair-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "5432:5432"

volumes:
    repair-postgres:
    