services:
    repair-app:
        container_name: repair-app
        build:
            context: .
            dockerfile: ./docker/development/Dockerfile
        volumes:
            - .:/app
        env_file:
            - .env
        restart: always
        ports:
            - 3000:3000
        depends_on:
            - repair-postgres

    repair-postgres:
        image: postgres:16.3-alpine
        volumes:
            - repair-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_DATABASE}
        ports:
            - ${DATABASE_PORT}:${DATABASE_PORT}

volumes:
    repair-postgres:
    